version: "3.6"
services:
  plex:
    cap_drop:
      - "AUDIT_CONTROL"
      - "BLOCK_SUSPEND"
      - "DAC_READ_SEARCH"
      - "IPC_LOCK"
      - "IPC_OWNER"
      - "LEASE"
      - "LINUX_IMMUTABLE"
      - "MAC_ADMIN"
      - "MAC_OVERRIDE"
      - "NET_ADMIN"
      - "NET_BROADCAST"
      - "SYSLOG"
      - "SYS_ADMIN"
      - "SYS_BOOT"
      - "SYS_MODULE"
      - "SYS_NICE"
      - "SYS_PACCT"
      - "SYS_PTRACE"
      - "SYS_RAWIO"
      - "SYS_RESOURCE"
      - "SYS_TIME"
      - "SYS_TTY_CONFIG"
      - "WAKE_ALARM"
    container_name: "plex"
    devices:
      - "/dev/dri:/dev/dri"
    entrypoint:
      - "/init"
    environment:
      - "PUID=${PUID}"
      - "PGID=${PGID}"
      - "VERSION=latest"
      - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      - "HOME=/root"
      - "LANGUAGE=en_US.UTF-8"
      - "LANG=en_US.UTF-8"
      - "TERM=xterm"
      - "S6_CMD_WAIT_FOR_SERVICES_MAXTIME=0"
      - "S6_VERBOSITY=1"
      - "S6_STAGE2_HOOK=/docker-mods"
      - "NVIDIA_DRIVER_CAPABILITIES=compute,video,utility"
      - "DEBIAN_FRONTEND=noninteractive"
      - "PLEX_DOWNLOAD=https://downloads.plex.tv/plex-media-server-new"
      - "PLEX_ARCH=amd64"
      - "PLEX_MEDIA_SERVER_APPLICATION_SUPPORT_DIR=/config/Library/Application Support"
      - "PLEX_MEDIA_SERVER_HOME=/usr/lib/plexmediaserver"
      - "PLEX_MEDIA_SERVER_MAX_PLUGIN_PROCS=6"
      - "PLEX_MEDIA_SERVER_USER=abc"
      - "PLEX_MEDIA_SERVER_INFO_VENDOR=Docker"
      - "PLEX_MEDIA_SERVER_INFO_DEVICE=Docker Container (LinuxServer.io)"
    image: "lscr.io/linuxserver/plex:latest"
    ipc: "private"
    labels:
      build_version: "Linuxserver.io version:- 1.29.2.6364-6d72b0cf6-ls145 Build-date:-\
        \ 2022-11-28T22:03:13-06:00"
      maintainer: "thelamer"
      org.opencontainers.image.authors: "linuxserver.io"
      org.opencontainers.image.created: "2022-11-28T22:03:13-06:00"
      org.opencontainers.image.description: "[Plex](https://plex.tv) organizes video,\
        \ music and photos from personal media libraries and streams them to smart\
        \ TVs, streaming boxes and mobile devices. This container is packaged as a\
        \ standalone Plex Media Server. has always been a top priority. Straightforward\
        \ design and bulk actions mean getting things done faster."
      org.opencontainers.image.documentation: "https://docs.linuxserver.io/images/docker-plex"
      org.opencontainers.image.licenses: "GPL-3.0-only"
      org.opencontainers.image.ref.name: "7ff02692193fbacbe42b237258e5044261de38e7"
      org.opencontainers.image.revision: "7ff02692193fbacbe42b237258e5044261de38e7"
      org.opencontainers.image.source: "https://github.com/linuxserver/docker-plex"
      org.opencontainers.image.title: "Plex"
      org.opencontainers.image.url: "https://github.com/linuxserver/docker-plex/packages"
      org.opencontainers.image.vendor: "linuxserver.io"
      org.opencontainers.image.version: "1.29.2.6364-6d72b0cf6-ls145"
    network_mode: "bridge"
    networks:
      server_net:
        ipv4_address: ${IP_ADDRESS}
    ports:
      - "32400:32400/tcp"
    restart: "always"
    volumes:
      - "plex_server_config:/config"
      - "nas_media:${NAS_MOUNT_PATH}"
    working_dir: "/"
    healthcheck:
      test: "curl --connect-timeout 15 --max-time 100 --silent --show-error --fail 'http://localhost:32400/identity' >/dev/null"
      interval: 1m 
      timeout: 15s 
      retries: 3 
      start_period: 1m
volumes:
  nas_media:
    external: true
  plex_server_config:
    external: true
networks:
  server_net:
    external: true