version: "3.6"
services:
  plex:
    cap_drop:
      - "AUDIT_CONTROL"
      - "BLOCK_SUSPEND"
      - "DAC_READ_SEARCH"
      - "IPC_LOCK"
      - "IPC_OWNER"
      - "LEASE"
      - "LINUX_IMMUTABLE"
      - "MAC_ADMIN"
      - "MAC_OVERRIDE"
      - "NET_ADMIN"
      - "NET_BROADCAST"
      - "SYSLOG"
      - "SYS_ADMIN"
      - "SYS_BOOT"
      - "SYS_MODULE"
      - "SYS_NICE"
      - "SYS_PACCT"
      - "SYS_PTRACE"
      - "SYS_RAWIO"
      - "SYS_RESOURCE"
      - "SYS_TIME"
      - "SYS_TTY_CONFIG"
      - "WAKE_ALARM"
    container_name: "file_browser"
    image: hurlenko/filebrowser
    user: "${UID}:${GID}"
    ports:
      - ${ACCESS_PORT}:8080/tcp
    volumes:
      - nas_shared_media:/data/media
      - nas_shared_documents:/data/documents
      - nas_backups_databases:/data/backups/databases
      - nas_backups_container_volumes:/data/backups/volumes
      - file_browser_data:/config
    environment:
      - FB_BASEURL=/filebrowser
    restart: always
    healthcheck:
      test: "wget --no-verbose --tries=1 --spider http://localhost:8080 || exit 1"
      interval: 60s
      timeout: 5s
      retries: 3
      start_period: 10s
volumes:
  nas_shared_media:
    external: true
  nas_backups_databases:
    external: true
  nas_backups_container_volumes:
    external: true
  nas_shared_documents:
    external: true
  file_browser_data:
    external: true