version: "3.6"
services:
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
      - $HOME/.docker/config.json:/config.json
    container_name: "watchtower"
    environment:
      - "WATCHTOWER_CLEANUP=true"
      - "WATCHTOWER_SCHEDULE=${SCHEDULE}"
      - "WATCHTOWER_DEBUG=${DEBUG}"
    restart: always
    healthcheck:
      test: "exit 0"
      interval: 180s
      timeout: 10s
      retries: 3
      start_period: 10s
    network_mode: "bridge"
    networks:
      server_net:
        ipv4_address: ${IP_ADDRESS}
networks:
  server_net:
    external: true