version: "3.6"
services:
  image_registry:
    cap_drop:
      - "AUDIT_CONTROL"
      - "BLOCK_SUSPEND"
      - "DAC_READ_SEARCH"
      - "IPC_LOCK"
      - "IPC_OWNER"
      - "LEASE"
      - "LINUX_IMMUTABLE"
      - "MAC_ADMIN"
      - "MAC_OVERRIDE"
      - "NET_ADMIN"
      - "NET_BROADCAST"
      - "SYSLOG"
      - "SYS_ADMIN"
      - "SYS_BOOT"
      - "SYS_MODULE"
      - "SYS_NICE"
      - "SYS_PACCT"
      - "SYS_PTRACE"
      - "SYS_RAWIO"
      - "SYS_RESOURCE"
      - "SYS_TIME"
      - "SYS_TTY_CONFIG"
      - "WAKE_ALARM"
    command:
      - "/etc/docker/registry/config.yml"
    container_name: "image_registry"
    entrypoint:
      - "/entrypoint.sh"
    environment:
      - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
    image: "registry:latest"
    ipc: "private"
    network_mode: "bridge"
    ports:
      - "5000:5000/tcp"
    restart: "always"
    volumes:
      - "image_registry_data:/var/lib/registry"
    healthcheck:
      test: "wget ${REGISTRY_URL} --spider || exit 1"
      interval: 2m
      timeout: 10s
volumes:
  image_registry_data:
    external: true