# Make sure you use your actual admin password...
MONITOR server-rack-ups@localhost 1 admin ADMIN_PASSWORD_HERE primary

MINSUPPLIES 1

SHUTDOWNCMD "/sbin/shutdown -h +0"

NOTIFYCMD /user/sbin/upssched

POLLFREQ 5
POLLFREQALERT 1
HOSTSYNC 15
DEADTIME 25
POWERDOWNFLAG "/etc/killpower"

NOTIFYFLAG ONLINE SYSLOG+WALL+EXEC
NOTIFYFLAG ONBATT SYSLOG+WALL+EXEC
NOTIFYFLAG LOWBATT SYSLOG+WALL+EXEC
NOTIFYFLAG FSD SYSLOG+WALL+EXEC
NOTIFYFLAG COMMOK SYSLOG+WALL+EXEC
NOTIFYFLAG COMMBAD SYSLOG+WALL+EXEC
NOTIFYFLAG SHUTDOWN SYSLOG+WALL+EXEC
NOTIFYFLAG REPLBATT SYSLOG+WALL+EXEC
NOTIFYFLAG NOCOMM SYSLOG+WALL+EXEC
NOTIFYFLAG NOPARENT SYSLOG+WALL+EXEC
NOTIFYFLAG DISCHRG SYSLOG+WALL+EXEC

OFFDURATION 30

RBWARNTIME 43200

NOCOMMWARNTIME 300

# You might also want to configure FINALDELAY and set it to a period long enough
# for your servers to all shut down, prior to the primary node shutting down and
# triggering the UPS to switch off its load, e.g. for 3 minutes:
FINALDELAY 90
