version: "3.6"
services:
  home_assistant:
    cap_drop:
      - "AUDIT_CONTROL"
      - "BLOCK_SUSPEND"
      - "DAC_READ_SEARCH"
      - "IPC_LOCK"
      - "IPC_OWNER"
      - "LEASE"
      - "LINUX_IMMUTABLE"
      - "MAC_ADMIN"
      - "MAC_OVERRIDE"
      - "NET_ADMIN"
      - "NET_BROADCAST"
      - "SYSLOG"
      - "SYS_ADMIN"
      - "SYS_BOOT"
      - "SYS_MODULE"
      - "SYS_NICE"
      - "SYS_PACCT"
      - "SYS_PTRACE"
      - "SYS_RAWIO"
      - "SYS_RESOURCE"
      - "SYS_TIME"
      - "SYS_TTY_CONFIG"
      - "WAKE_ALARM"
    container_name: "home_assistant"
    entrypoint:
      - "/init"
    environment:
      - "PATH=/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      - "LANG=C.UTF-8"
      - "S6_BEHAVIOUR_IF_STAGE2_FAILS=2"
      - "S6_CMD_WAIT_FOR_SERVICES_MAXTIME=0"
      - "S6_CMD_WAIT_FOR_SERVICES=1"
      - "S6_SERVICES_READYTIME=50"
      - "WHEELS_LINKS=https://wheels.home-assistant.io/musllinux/"
      - "S6_SERVICES_GRACETIME=220000"
    image: "docker.io/homeassistant/home-assistant:latest"
    ipc: "private"
    labels:
      docker-volume-backup.stop-during-backup: true
    network_mode: "bridge"
    networks:
      server_net:
        ipv4_address: ${IP_ADDRESS}
    ports:
      - "8123:8123/tcp"
    privileged: true
    restart: "unless-stopped"
    security_opt:
      - "label=disable"
    volumes:
      - "home_assistant_data:/config"
    working_dir: "/config"
    healthcheck:
      test: "curl --connect-timeout 10 --silent -f http://localhost:8123/ || exit 1 "
      interval: 20s
      timeout: 10s
      retries: 5 
      start_period: 30s
volumes:
  home_assistant_data:
    external: true
networks:
  server_net:
    external: true
