version: "3.6"
services:
  volumes_backup:
    cap_drop:
      - "AUDIT_CONTROL"
      - "BLOCK_SUSPEND"
      - "DAC_READ_SEARCH"
      - "IPC_LOCK"
      - "IPC_OWNER"
      - "LEASE"
      - "LINUX_IMMUTABLE"
      - "MAC_ADMIN"
      - "MAC_OVERRIDE"
      - "NET_ADMIN"
      - "NET_BROADCAST"
      - "SYSLOG"
      - "SYS_ADMIN"
      - "SYS_BOOT"
      - "SYS_MODULE"
      - "SYS_NICE"
      - "SYS_PACCT"
      - "SYS_PTRACE"
      - "SYS_RAWIO"
      - "SYS_RESOURCE"
      - "SYS_TIME"
      - "SYS_TTY_CONFIG"
      - "WAKE_ALARM"
    container_name: "volumes_backup"
    image: offen/docker-volume-backup:latest
    environment:
      BACKUP_FILENAME: backup-%Y-%m-%dT%H-%M-%S.tar.gz
      BACKUP_PRUNING_PREFIX: backup-
      BACKUP_RETENTION_DAYS: 5
      BACKUP_CRON_EXPRESSION: ${CRON_SCHEDULE}
      SSH_HOST_NAME: ${SSH_HOST}
      SSH_PORT: 22
      SSH_USER: ${SSH_USER}
      SSH_PASSWORD: ${SSH_PASSWORD}
      SSH_REMOTE_PATH: ${SSH_PATH}
    network_mode: "bridge"
    #entrypoint: backup
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - file_browser_data:/backup/file_browser_data:ro
      - keg_monitor_app_data:/backup/keg_monitor_app_data:ro
      - mqtt_broker_config:/backup/mqtt_broker_config:ro
      - mqtt_broker_data:/backup/mqtt_broker_data:ro
      - mqtt_broker_log:/backup/mqtt_broker_log:ro
      - pgadmin_data:/backup/pgadmin:ro
      - plex_server_config:/backup/plex_server_config:ro
      - portainer_data:/backup/portainer_data:ro
      - postgresql_data:/backup/postgresql_data:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: always
    healthcheck:
      test: "exit 0"
      interval: 60s
      timeout: 5s
      retries: 3
      start_period: 10s
volumes:
  file_browser_data:
    external: true
  keg_monitor_app_data:
    external: true
  mqtt_broker_config:
    external: true
  mqtt_broker_data:
    external: true
  mqtt_broker_log:
    external: true
  pgadmin_data:
    external: true
  plex_server_config:
    external: true
  portainer_data:
    external: true
  postgresql_data:
    external: true