version: "3.6"
services:
  mqtt_broker:
    cap_drop:
      - "AUDIT_CONTROL"
      - "BLOCK_SUSPEND"
      - "DAC_READ_SEARCH"
      - "IPC_LOCK"
      - "IPC_OWNER"
      - "LEASE"
      - "LINUX_IMMUTABLE"
      - "MAC_ADMIN"
      - "MAC_OVERRIDE"
      - "NET_ADMIN"
      - "NET_BROADCAST"
      - "SYSLOG"
      - "SYS_ADMIN"
      - "SYS_BOOT"
      - "SYS_MODULE"
      - "SYS_NICE"
      - "SYS_PACCT"
      - "SYS_PTRACE"
      - "SYS_RAWIO"
      - "SYS_RESOURCE"
      - "SYS_TIME"
      - "SYS_TTY_CONFIG"
      - "WAKE_ALARM"
    command:
      - "/usr/sbin/mosquitto"
      - "-c"
      - "/mosquitto/config/mosquitto.conf"
    container_name: "mqtt_broker"
    entrypoint:
      - "/docker-entrypoint.sh"
    environment:
      - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      - "VERSION=2.0.15"
      - "DOWNLOAD_SHA256=4735b1d32e3f91c7a8896741d88a3022e89730a1ee897946decfa0df27039ac6"
      - "GPG_KEYS=A0D6EEA1DCAE49A635A3B2F0779B22DFB3E717B7"
      - "LWS_VERSION=4.2.1"
      - "LWS_SHA256=842da21f73ccba2be59e680de10a8cce7928313048750eb6ad73b6fa50763c51"
    labels:
      - docker-volume-backup.stop-during-backup=true
    image: "eclipse-mosquitto:latest"
    ipc: "private"
    network_mode: "bridge"
    ports:
      - "1883:1883/tcp"
    restart: "always"
    volumes:
      - "mqtt_broker_config:/mosquitto/config"
      - "mqtt_broker_data:/mosquitto/data"
      - "mqtt_broker_log:/mosquitto/log"
    healthcheck:
      test: "timeout 3 mosquitto_sub -h localhost -p 1883 -u ${HEALTHCHECK_PROBE_USER} -P ${HEALTHCHECK_PROBE_PASSWORD} -t 'topic' -E -i probe"
      interval: 30s
      timeout: 5s
volumes:
  mqtt_broker_config:
    external: true
  mqtt_broker_data:
    external: true
  mqtt_broker_log:
    external: true