version: "3.6"
services:
  vs_code:
    image: "codercom/code-server:latest"
    container_name: "vs_code"
    environment:
      - "PASSWORD=${PASSWORD}"
    ipc: "private"
    network_mode: "bridge"
    networks:
      server_net:
        ipv4_address: ${IP_ADDRESS}
    ports:
      - ${ACCESS_PORT}:8080/tcp
    restart: "unless-stopped"
    volumes:
      - vscode_data:/home/coder/.local/share/code-server
      - home_assistant_data:/home/coder/projects/home_assistant
    healthcheck:
      test: "curl --connect-timeout 10 --silent -f http://localhost:8080/ || exit 1 "
      interval: 30s
      timeout: 10s
      retries: 5 
      start_period: 20s
volumes:
  vscode_data:
    external: true
  home_assistant_data:
    external: true
networks:
  server_net:
    external: true