version: "3.6"
services:
  cloudflare_ddns:
    image: "oznu/cloudflare-ddns:latest"
    container_name: "cloudflare_ddns"
    environment:
      - "API_KEY=${API_KEY}"
      - "ZONE=${ZONE}"
      - "PROXIED=false"
      - "CRON=${CRON_SCHEDULE}"
    ipc: "private"
    network_mode: "bridge"
    networks:
      server_net:
        ipv4_address: ${IP_ADDRESS}
    restart: "always"
    healthcheck:
      test: "ping -c 1 www.google.com || exit 1"
      interval: 5m
      timeout: 10s
      retries: 3
      start_period: 20s
networks:
  server_net:
    external: true